app = 'web-icy-log-2807'
primary_region = 'ord'

[build]

[env]
  NEXT_PUBLIC_SERVER_URL = 'https://api-white-water-964.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
