version: "3"
services:
  web:
    container_name: web
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}

  api:
    container_name: api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network
    environment:
      - NODE_ENV=production
      - PORT=${API_PORT:-3001}
    volumes:
      - ./apps/api/user_dbs:/app/user_dbs

networks:
  app_network:
    name: app_network
    driver: bridge
